import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Script from "next/script";
import IntercomClientComponent from "@/components/IntercomClientComponent";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {children}
        <Script
            strategy="afterInteractive"
            id="intercom-settings"
            dangerouslySetInnerHTML={{
                __html: `
                        window.intercomSettings = {
                            api_base: "https://api-iam.intercom.io",
                            app_id: "rxehm4ny", // Ensure this matches your actual Intercom app ID.
                        };
                    `
            }}
        />
        <IntercomClientComponent/>
        </body>
        </html>
    );
}
